platform :ios, '9.0'

target 'GoTapp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GoTapp
  pod 'Alamofire'
  pod 'AlamofireImage'
  
  
  

  target 'GoTappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoTappUITests' do
    # Pods for testing
  end

end
